### ISSUE TITLE
Unable to create group discussion board

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#434] opened 2022-08-10 17:44 UTC
I was going to test the reply by email groups function just now, and I got a strange error while creating a group discussion board on dev. I'm logged in as Walter Test (hctester70). At the point in the group creation process where I check the box for "Yes. I want this group to have a discussion board" and hit the next step button, the page tries to load for about 40 seconds and then I'm getting the error message below. The only way I can get past this is to go back and uncheck the discussion box. ![Screen Shot 2022-08-10 at 1.37.42 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/71fd44a3-ebb0-442c-a470-3f230c21378f)

**Comment by bjr70** [comment] 2022-08-10 17:54
I was able to replicate this with Barty's Party Palace on dev with Barty Test. This is not happening on Prod. 

The group was created and I was able to access it, but when I tried to enable discussion from the settings I received the same error.

**Comment by mikethicke** [comment] 2022-08-11 11:55
I believe this is related to MESH-Research/commons#242 , which was originally addressed by https://github.com/MESH-Research/hc-custom/commit/b4cb52d2ff7acd642b7f1060d0117bfab30a6f7c .

This latest issue seems to be caused by 

1.  Max execution time being set to 30 seconds (the default). This is perhaps due to the PHP 7.4 update. I increased max execution time to 300 seconds. (It is generally preferable to have a very slow page load to a 504 timeout.)
2. The workaround to MESH-Research/commons#242 missing a possible case that led to latest topic id being recalculated unnecessarily. This is addressed by https://github.com/MESH-Research/hc-custom/commit/89473d737d8f9cf5976364e1e34fb7c5d7b90c86

The root cause of this is bbpress being extremely inefficient when there is a large number of discussion forums.

**Comment by bjr70** [comment] 2022-08-15 14:50
Fixed.

**Closed by bjr70** 2022-08-15 14:50 UTC
