### ISSUE TITLE
MIssing content - MLA Commons forums and committee groups on dev 

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#145] opened 2021-09-21 18:22 UTC
- [ ] Add to an appropriate Epic.

Tester (if different from issue creator): Anne
Site: MLA Commons
URL:  e.g. https://mla.hcommons-dev.org/groups/medieval/
Test Account: hctester10, adonlon
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? no

**Describe the issue**
This may be an issue with the sync. But in case not: the MLA Commons forums and committee groups I've looked at do not display content. The group menu and header displays, but the content of the group's pages (activity feed, member list, etc.) is empty. 

One effect of this is also that I don't get the popup notification with information about setting notifications (it must be triggered by something that's not loading on the page). I assume that once the content is present this will not be an issue. 

This doesn't seem to be an issue with other kinds of groups on MLA Commons or any groups (including committees) on other networks. 

**To Reproduce**
1. Go to https://mla.hcommons-dev.org/groups/medieval/
2. View the activity feed, member page, etc. They are empty.

**Expected behavior**
It should look something like https://mla.hcommons.org/groups/medieval/

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment] 2021-09-23 13:24
I think this is a genuine issue, not an issue with sync.

**Comment by mikethicke** [comment] 2021-09-23 20:36
Seems to have been caused by a problem loading the cURL extension. Should be fixed now.

**Comment by adonlon** [comment] 2021-09-23 20:39
Confirmed! I can see the forum groups' content and it fixed the CORE issue, too.

**Closed** 2021-11-01 15:26 UTC
Labels: website-issue, needs-review
