### ISSUE TITLE
hcommons-dev enrollment issue

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#106] opened 2021-08-30 18:16 UTC
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Bonnie
Site: hcommons-dev
URL: hcommons-dev.org
Test Account: Dave Test
Area (CORE, sites, profiles, groups, general): Enrollment
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Users are not receiving the correct role on enrollment. This causes users not to be able to create a group and to cause other functionality to go missing

**To Reproduce**
Enroll user
Log into hcommons-dev.org/wp-admin to check the user role

**Expected behavior**

**Screenshots**
![no-role-wp-admin.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/fa584613-575e-4212-943a-80ca27bc44de)

## Optional details, if they seem relevant

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 92.0.902.84 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
When trying to invite Dave Test to an existing group, the search fails to find him.

**Comment by ericknappe** [comment] 2021-09-07 13:54
This was caused by the dev grouper loader process going offline. This is not a problem with any of the upgraded plugins. After restarting processes on dev_grouper I was able to correctly enroll hctester20.

**Comment by ericknappe** [comment] 2021-09-07 13:55
dev_grouper process restart commands

#restart tomcat
sudo service tomcat6 stop
sudo service tomcat6 start

#restart grouper loader process
cd /opt/grouper/grouper.apiBinary-2.2.2
sudo /etc/init.d/grouper_loader restart

#sync one user
cd /opt/grouper/grouper.apiBinary-2.2.2
sudo -u tomcat6 MEM_MAX=2048m ./bin/gsh.sh -psp -sync hctester20

**Comment by bjr70** [comment] 2021-09-13 14:54
It's still not populating name in profiles on enrollment. See https://up.hcommons-dev.org/members/hctester40/.

**Comment by mikethicke** [comment] 2021-09-13 17:23
Fixed by restarting grouper-dev

**Closed by mikethicke** 2021-09-13 17:23 UTC
Labels: website-issue, needs-review
